name: CI/CD Pipeline

on:
  push:
    # Monitora commits para a branch "main"
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuração do Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      # Instalar dependências
      - name: Install dependencies
        run: npm install

      # Executar testes
      - name: Run unit tests
        run: npm test

      # Build do projeto
      - name: Build project
        run: npm run build

  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      # Checkout do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuração do Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      # Instalar dependências
      - name: Install dependencies
        run: npm install

      # Publicar no npm
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
